# Generated by Django 5.1.3 on 2024-11-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lift_passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_passenger', models.IntegerField()),
                ('initial', models.IntegerField()),
                ('destination', models.IntegerField()),
                ('time_slot', models.DateTimeField()),
            ],
        ),
    ]
